<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
   <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
   <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0" />
   <title>DevNet - Blog</title>
   <!-- styles -->
   <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css">
   <link rel="stylesheet" href="/lib/bootstrap-icons/font/bootstrap-icons.css">
   <link rel="stylesheet" href="/css/style.css">
</head>
<body class="d-flex flex-column h-100">
   <header>
      <?= $this->renderPartial('Shared/Navbar') ?>
   </header>
   <main class="flex-shrink-0">
      <?= $this->renderBody() ?>
   </main>
   <footer class="footer border-top mt-auto py-3 bg-white">
      <?= $this->renderPartial('Shared/Footer') ?>
   </footer>
   <!-- scripts -->
   <script src="/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
</body>
</html>