<nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom shadow-sm">
   <div class="container">
      <a class="navbar-brand" href="/">Expresser</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
         <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
               <a class="nav-link" href="/blog">Blog</a>
            </li>
            <li class="nav-item">
               <a class="nav-link" href="/home/about">About</a>
            </li>
            <li class="nav-item">
               <a class="nav-link" href="/home/contact">Contact</a>
            </li>
         </ul>
         <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <form class="d-flex" method="get" action="/home/search">
               <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            </form>
            <li class="nav-item dropdown">
               <a class="nav-link dropdown-toggle py-1" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="bi bi-person-circle fs-4 lh-1"></i>
               </a>
               <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="/user/account">My Account</a></li>
                  <li><a class="dropdown-item" href="/user/account/register">Register</a></li>
                  <li>
                     <hr class="dropdown-divider">
                  </li>
                  <li><a class="dropdown-item" href="/user/account/logout">Log Out</a></li>
               </ul>
            </li>
         </ul>
      </div>
   </div>
</nav>