<nav class="pt-4" style="position: sticky; top: 0; min-height: 100vh; overflow: auto">
   <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
         <a class="nav-link link-dark" href="/user/account">
            <span class="d-inline-block bi me-2" style="width:16px; height:16px;">
               <i class="bi bi-house-door"></i>
            </span>
            Home
         </a>
      </li>
      <li>
         <a class="nav-link link-dark" href="#">
            <span class="d-inline-block bi me-2" style="width:16px; height:16px;">
               <i class="bi bi-file-earmark-text"></i>
            </span>
            Articles
         </a>
      </li>
      <li>
         <a class="nav-link link-dark" href="#">
            <span class="d-inline-block bi me-2" style="width:16px; height:16px;">
               <i class="bi bi-chat-square-text"></i>
            </span>
            Comments
         </a>
      </li>
      <li>
         <a class="nav-link link-dark" href="#">
            <span class="d-inline-block bi me-2" style="width:16px; height:16px;">
               <i class="bi bi-camera"></i>
            </span>
            Media
         </a>
      </li>
      <li>
         <a class="nav-link link-dark" href="#">
            <span class="d-inline-block bi me-2" style="width:16px; height:16px;">
               <i class="bi bi-hand-thumbs-up"></i>
            </span>
            Likes
         </a>
      </li>
      <li>
         <a class="nav-link link-dark" href="#">
            <span class="d-inline-block bi me-2" style="width:16px; height:16px;">
               <i class="bi bi-person"></i>
            </span>
            Account
         </a>
      </li>
   </ul>
</nav>