<?= $this->layout('Shared/layout') ?>

<!-- Include stylesheet -->
<link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">

<div class="container">
   <div class="row">
      <aside class="bg-white" style="width: 200px;">
         <?= $this->renderPartial('Shared/userSidebar') ?>
      </aside>
      <div class="d-flex flex-grow-1 flex-column px-4 py-3" style="min-height: 500px; width: 400px">
         <header class="px-1">
            <div class="row">
               <div class="col">
                  <h3 class="mb-3" style="color: #555">New Article</h3>
               </div>
               <div class="col">
                  <nav aria-label="breadcrumb" style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);">
                     <ol class="breadcrumb justify-content-end mt-1">
                        <li class="breadcrumb-item"><a class="text-decoration-none" href="/user/account">User</a></li>
                        <li class="breadcrumb-item"><a class="text-decoration-none" href="/user/posts">Articles</a></li>
                        <li class="breadcrumb-item active" aria-current="page">New</li>
                     </ol>
                  </nav>
               </div>
            </div>
         </header>
         <form method="post" action="/user/posts/new">
            <div class="row g-3">
               <div class="col-lg-8">
                  <div class="bg-white border shadow-sm mb-3">
                     <div class="m-3">
                        <input type="text" class="form-control border-0 border-bottom" id="title" name="Title" placeholder="Title">
                     </div>
                  </div>
                  <textarea id="content" name="Content" style="display: none;"></textarea>
                  <div id="editor" style="height: 395px;"></div>
               </div>
               <div class="col-lg-4">
                  <div class="card shadow-sm">
                     <div class="card-header bg-white">
                        <div class="my-2">
                           <a class="btn btn-outline-secondary" style="width: 49%;" href="/user/posts"><i class="bi bi-x-lg me-1"></i>Cancel</a>
                           <button type="submit" class="btn btn-primary" style="width: 49%;"><i class="bi bi-check-lg me-1"></i>Save</button>
                        </div>
                     </div>
                     <div class="card-body">
                        <div class="accordion accordion-flush" id="meta-data">
                           <div class="accordion-item">
                              <h2 class="accordion-header" id="heading-status">
                                 <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-status" aria-expanded="true" aria-controls="collapse-status">
                                    Status
                                 </button>
                              </h2>
                              <div id="collapse-status" class="accordion-collapse collapse show" aria-labelledby="heading-status" data-bs-parent="#meta-data">
                                 <div class="accordion-body">
                                    <select class="form-select" id="status" name="Status">
                                       <option value="1">Draft</option>
                                       <option value="2">Published</option>
                                       <option value="3">Archived</option>
                                    </select>
                                 </div>
                              </div>
                           </div>
                           <div class="accordion-item">
                              <h2 class="accordion-header" id="heading-date">
                                 <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-date" aria-expanded="false" aria-controls="collapse-date">
                                    Date
                                 </button>
                              </h2>
                              <div id="collapse-date" class="accordion-collapse collapse" aria-labelledby="heading-date" data-bs-parent="#meta-data">
                                 <div class="accordion-body">
                                    <input type="date" class="form-control" id="date" name="Date">
                                 </div>
                              </div>
                           </div>
                           <div class="accordion-item">
                              <h2 class="accordion-header" id="heading-sections">
                                 <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-sections" aria-expanded="false" aria-controls="collapse-sections">
                                    Sections
                                 </button>
                              </h2>
                              <div id="collapse-sections" class="accordion-collapse collapse" aria-labelledby="heading-sections" data-bs-parent="#meta-data">
                                 <div class="accordion-body">
                                    <select class="form-select" id="section" name="Section">
                                       <option value="1">Events</option>
                                       <option value="2">News</option>
                                       <option value="3">Trending</option>
                                    </select>
                                 </div>
                              </div>
                           </div>
                           <div class="accordion-item">
                              <h2 class="accordion-header" id="heading-image">
                                 <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-image" aria-expanded="false" aria-controls="collapse-image">
                                    Image
                                 </button>
                              </h2>
                              <div id="collapse-image" class="accordion-collapse collapse" aria-labelledby="heading-image" data-bs-parent="#meta-data">
                                 <div class="accordion-body">
                                    <div class="input-group">
                                       <input type="text" class="form-control" id="image" name="Image" aria-label="Recipient's username" aria-describedby="button-addon">
                                       <button type="button" class="btn btn-outline-secondary" id="open">Open</button>
                                    </div>
                                 </div>
                              </div>
                           </div>
                           <div class="accordion-item">
                              <h2 class="accordion-header" id="heading-excerpt">
                                 <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-excerpt" aria-expanded="false" aria-controls="collapse-excerpt">
                                    Excerpt
                                 </button>
                              </h2>
                              <div id="collapse-excerpt" class="accordion-collapse collapse" aria-labelledby="heading-excerpt" data-bs-parent="#meta-data">
                                 <div class="accordion-body">
                                    <textarea class="form-control" id="excerpt" name="Excerpt" rows="3"></textarea>
                                 </div>
                              </div>
                           </div>
                           <div class="accordion-item">
                              <h2 class="accordion-header" id="heading-permalink">
                                 <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-permalink" aria-expanded="false" aria-controls="collapse-permalink">
                                    Permalink
                                 </button>
                              </h2>
                              <div id="collapse-permalink" class="accordion-collapse collapse" aria-labelledby="heading-permalink" data-bs-parent="#meta-data">
                                 <div class="accordion-body">
                                    <input type="text" class="form-control" id="slug" name="Slug">
                                 </div>
                              </div>
                           </div>
                           <div class="accordion-item">
                              <h2 class="accordion-header" id="heading-options">
                                 <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-options" aria-expanded="false" aria-controls="collapse-options">
                                    Options
                                 </button>
                              </h2>
                              <div id="collapse-options" class="accordion-collapse collapse" aria-labelledby="heading-options" data-bs-parent="#meta-data">
                                 <div class="accordion-body">
                                    <div>
                                       <input class="form-check-input" type="checkbox" id="commented" name="Commented" checked>
                                       <label class="form-check-label" for="commented">Allow Comments</label>
                                    </div>
                                    <div>
                                       <input class="form-check-input" type="checkbox" id="featured" name="Featured">
                                       <label class="form-check-label" for="featured">Featured</label>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </form>
      </div>
   </div>
</div>

<!-- Include the Quill library -->
<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>

<!-- Initialize Quill editor -->
<script>
   var toolbarOptions = [
      [{
         'font': []
      }],
      [{
         'header': [1, 2, 3, 4, 5, 6, false]
      }],
      ['bold', 'italic', 'underline', 'strike'], // toggled buttons
      [{
         'color': []
      }, {
         'background': []
      }], // dropdown with defaults from theme
      [{
         'script': 'sub'
      }, {
         'script': 'super'
      }], // superscript/subscript
      [{
         'list': 'ordered'
      }, {
         'list': 'bullet'
      }],
      [{
         'direction': 'rtl'
      }, , {
         'align': []
      }], // text direction
      ['blockquote', 'code-block'],
      ['clean'] // remove formatting button
   ];

   var quill = new Quill('#editor', {
      modules: {
         toolbar: toolbarOptions
      },
      theme: 'snow'
   });

   quill.on('text-change', update);
   update();

   function update() {
      var content = document.querySelector('#content');
      content.innerHTML = quill.root.innerHTML;
   }

   var date = document.getElementById('date');
   if (!date.value) {
      date.valueAsDate = new Date();
   }

   var title = document.getElementById('title');
   title.onchange = function() {
      var slug = document.getElementById('slug');
      slug.value = title.value.replace(/ /g, '-');
   }

   var open = document.getElementById('open');
   open.onclick = function() {
      var input = document.createElement('input');
      input.type = 'file';
      input.onchange = function() {
         var files = Array.from(input.files);
         var image = document.getElementById('image');
         image.value = files[0].name;
      };
      input.click();
   }
</script>