<?= $this->layout('Shared/Layout') ?>

<div class="d-flex flex-column justify-content-center text-center" style="height: 250px; background-image: url(/images/113-800x200.jpg); background-size: cover;">
   <h1 class="text-info display-2 mx-auto fw-normal" style="text-shadow: 2px 2px 8px #000;">About Us</h1>
   <p class="lead w-75 mx-auto text-white fw-normal" style="text-shadow: 2px 2px 8px #000;">This is what we do</p>
</div>
<div class="container">
   <article>
      <br><br>
      <p>
         Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus ad minus omnis ut fugiat laudantium, tempore dolor facilis totam, nesciunt voluptatibus deleniti aspernatur, ratione unde alias aliquam molestias. Eaque, cumque.
      </p>
      <p>
         Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem perspiciatis sapiente doloremque ex iste at, perferendis eligendi illum laudantium impedit neque, quae facilis? Modi ut accusantium eos facilis error dolor.
      </p>
      <p>
         Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur ducimus eligendi, tenetur tempora placeat sit beatae sunt, eum dignissimos quasi quidem assumenda obcaecati, at quo possimus adipisci aspernatur deserunt nesciunt.
      </p>
      <br><br>
   </article>
</div>
