<?= $this->layout('Shared/Layout') ?>

<div class="d-flex flex-column justify-content-center text-center" style="height: 250px; background-image: url(/images/442-800x200.jpg); background-size: cover;">
   <h1 class="text-warning display-2 mx-auto fw-normal" style="text-shadow: 2px 2px 8px #000;">Contact Us</h1>
   <p class="lead w-75 mx-auto text-white fw-normal" style="text-shadow: 2px 2px 8px #000;">We have answers</p>
</div>
<div class="container">
    <section class="page-section" id="contact">
        <br><br>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda consectetur asperiores magnam dolorem mollitia quibusdam ut nisi quidem. Modi saepe optio amet odit deserunt nihil quidem rerum eligendi error molestias.
        </p>
        <br>
        <form id="contactForm" method="post" action="/home/contact">
            <div class="row align-items-stretch mb-3">
                <div class="col-md-6">
                     <div class="mb-3">
                        <input type="text" class="form-control" id="name" name="Name" placeholder="Name" required>
                     </div>
                     <div class="mb-3">
                        <input type="email" class="form-control" id="email" name="Email" placeholder="Email" required>
                     </div>
                     <div class="mb-3">
                        <input type="text" class="form-control" id="subject" name="Subject" placeholder="Subject" required>
                     </div>
                  </div>
                  <div class="col-md-6">
                     <div class="form-group form-group-textarea mb-3" style="height: 9.1rem;">
                        <textarea class="form-control h-100" id="message" name="Message" placeholder="Message" required></textarea>
                     </div>
                  </div>
               </div>
            <div class="text-center">
                <button class="btn btn-primary btn-xl text-uppercase" id="sendMessageButton" type="submit">Send Message</button>
            </div>
        </form>
        <br><br>
    </section>
</div>
