<? $this->layout('Shared/layout') ?>

<div class="container">
   <div class="row">
      <aside class="bg-white" style="width: 200px;">
         <? $this->renderPartial('Shared/userSidebar') ?>
      </aside>
      <div class="d-flex flex-grow-1 flex-column px-4 py-3" style="min-height: 500px; width: 400px">
         <header class="px-1 mb-3" style="border-bottom: 1px solid #bbb;">
            <div class="row">
               <div class="col">
                  <h3 class="mb-3" style="color: #555">Dashboard</h3>
               </div>
               <div class="col">
                  <nav aria-label="breadcrumb" style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);">
                     <ol class="breadcrumb justify-content-end mt-1">
                        <li class="breadcrumb-item"><a class="text-decoration-none" href="/user/account">User</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Account</li>
                     </ol>
                  </nav>
               </div>
            </div>
         </header>
         <div class="card shadow-sm mb-3">
            <div class="card-body">
               <div class="row justify-content-center row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4">
                  <div class="col">
                     <img class="img-fluid" src="/icons/user-icon.svg" alt="...">
                  </div>
                  <div class="col">
                     <h5 class="card-title">John Doe</h5>
                     <h6 class="card-subtitle text-muted mb-2">Author</h6>
                     <p class="card-text mb-2">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla cupiditate non adipisci nesciunt.
                     </p>
                  </div>
                  <div class="col">
                     <div class="mb-1">
                        <i class="bi bi-geo-alt fs-5 align-middle me-2"></i><span class="align-middle">Location</span>
                     </div>
                     <div class="mb-1">
                        <i class="bi bi-envelope fs-5 align-middle me-2"></i><span class="align-middle">john.doe@email.com</span>
                     </div>
                     <div class="mb-1">
                        <i class="bi bi-link-45deg fs-5 align-middle me-2"></i><span class="align-middle">www.website.com</span>
                     </div>
                  </div>
                  <div class="col">
                     <div class="d-flex flex-row justify-content-center pt-2">
                        <div class="text-center m-auto">
                           <h6 class="card-title">Followers</h6>
                           <p class="card-text fs-6">234</p>
                        </div>
                        <div class="border-end"></div>
                        <div class="text-center m-auto">
                           <h6 class="card-title">Followings</h6>
                           <p class="card-text fs-6">24</p>
                        </div>
                     </div>
                     <div class="text-center py-3">
                        <a class="btn btn-primary" href="/user/account/edit">Edit Account</a>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <section class="mb-3">
            <div class="row row-cols-1 row-cols-lg-2 row-cols-xl-4 g-3">
               <div class="col">
                  <div class="card flex-row h-100 shadow-sm">
                     <div class="card-header border-bottom-0">
                        <i class="bi bi-file-earmark-text fs-1"></i>
                     </div>
                     <div class="card-body text-end">
                        <h5 class="card-title">Articles</h5>
                        <p class="card-text">456</p>
                     </div>
                  </div>
               </div>
               <div class="col">
                  <div class="card flex-row h-100 shadow-sm">
                     <div class="card-header border-bottom-0">
                        <i class="bi bi-chat-square-text fs-1"></i>
                     </div>
                     <div class="card-body text-end">
                        <h5 class="card-title">Comments</h5>
                        <p class="card-text">456</p>
                     </div>
                  </div>
               </div>
               <div class="col">
                  <div class="card flex-row h-100 shadow-sm">
                     <div class="card-header border-bottom-0">
                        <i class="bi bi-hand-thumbs-up fs-1"></i>
                     </div>
                     <div class="card-body text-end">
                        <h5 class="card-title">Likes</h5>
                        <p class="card-text">456</p>
                     </div>
                  </div>
               </div>
               <div class="col">
                  <div class="card flex-row h-100 shadow-sm">
                     <div class="card-header border-bottom-0">
                        <i class="bi bi-camera fs-1"></i>
                     </div>
                     <div class="card-body text-end">
                        <h5 class="card-title">Media</h5>
                        <p class="card-text">456</p>
                     </div>
                  </div>
               </div>
            </div>
         </section>
         <section>
            <div class="row row-cols-1 row-cols-lg-2 g-3">
               <div class="col">
                  <div class="card shadow-sm">
                     <h5 class="card-header">Published Articles</h5>
                     <div class="card-body">
                        <div>
                           <canvas id="PostChart"></canvas>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="col">
                  <div class="card shadow-sm">
                     <h5 class="card-header">Gained Views</h5>
                     <div class="card-body">
                        <div>
                           <canvas id="ViewChart"></canvas>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </section>
      </div>
   </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.2.1/chart.min.js"></script>
<script>
   const labels = [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
   ];
   const posts = {
      labels: labels,
      datasets: [{
         label: 'Monthley Posts',
         backgroundColor: 'rgb(255, 99, 132)',
         borderColor: 'rgb(255, 99, 132)',
         data: [0, 10, 5, 2, 20, 30],
      }]
   };
   const views = {
      labels: labels,
      datasets: [{
         label: 'Monthley Views',
         backgroundColor: 'rgb(132, 99, 255)',
         borderColor: 'rgb(132, 99, 255)',
         data: [0, 10, 5, 2, 20, 30],
      }]
   };

   const PostConfig = {
      type: 'bar',
      data: posts,
      options: {}
   };

   const ViewConfig = {
      type: 'line',
      data: views,
      options: {}
   };

   var PostChart = new Chart(
      document.getElementById('PostChart'),
      PostConfig
   );

   var ViewChart = new Chart(
      document.getElementById('ViewChart'),
      ViewConfig
   );
</script>