<? $this->layout('Shared/layout') ?>

<header class="d-flex flex-column justify-content-center border-bottom" style="height: 100px; background-color: #f8f9fa;">
   <div class="container">
      <div class="row">
         <div class="col">
            <h4 class="my-1" style="color: #555">Dashboard</h4>
         </div>
         <div class="col">
            <nav aria-label="breadcrumb" style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);">
               <ol class="breadcrumb justify-content-end my-1">
                  <li class="breadcrumb-item"><a class="text-decoration-none" href="/user/account">User</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Account</li>
               </ol>
            </nav>
         </div>
      </div>
   </div>
</header>
<div class="container">
   <div class="row">
      <aside class="" style="width: 200px;">
         <? $this->renderPartial('Shared/userSidebar') ?>
      </aside>
      <div class="d-flex flex-grow-1 flex-column px-4 py-3" style="min-height: 500px; width: 400px">
         <div class="card border-0 h-100">
            <div class="row row-cols-1 row-cols-sm-1 row-cols-lg-2">
               <div class="col d-flex flex-column flex-lg-row align-items-center">
                  <div class="card-header border-0 bg-white">
                     <img class="img-fluid m-auto" style="max-height: 100px;" src="/icons/user-icon.svg" alt="...">
                  </div>
                  <div class="card-body">
                     <div class="d-flex flex-column justify-content-center h-100">
                        <h5 class="card-title">John Doe</h5>
                        <h6 class="card-subtitle text-muted mb-2">Author</h6>
                     </div>
                  </div>
               </div>
               <div class="col d-flex justify-content-center">
                  <div class="card-footer w-100 bg-white border-0">
                     <div class="d-flex flex-row h-100">
                        <div class="text-center px-3 m-auto">
                           <h6 class="card-title">Followers</h6>
                           <h6 class="card-subtitle text-muted mb-2">234</h6>
                        </div>
                        <div class="border-end my-3"></div>
                        <div class="text-center px-3 m-auto">
                           <h6 class="card-title">Followings</h6>
                           <h6 class="card-subtitle text-muted mb-2">24</h6>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <section class="mb-3">
            <div class="row row-cols-1 row-cols-lg-2 row-cols-xl-4 g-3">
               <div class="col">
                  <div class="card flex-row shadow-sm">
                     <div class="card-header border-bottom-0 d-flex align-items-center">
                        <i class="bi bi-file-earmark-text fs-2"></i>
                     </div>
                     <div class="card-body text-end">
                        <h6 class="card-title">Articles</h6>
                        <h6 class="card-subtitle text-muted mb-2">456</h6>
                     </div>
                  </div>
               </div>
               <div class="col">
                  <div class="card flex-row shadow-sm">
                     <div class="card-header border-bottom-0 d-flex align-items-center">
                        <i class="bi bi-chat-square-text fs-2"></i>
                     </div>
                     <div class="card-body text-end">
                        <h6 class="card-title">Comments</h6>
                        <h6 class="card-subtitle text-muted mb-2">456</h6>
                     </div>
                  </div>
               </div>
               <div class="col">
                  <div class="card flex-row shadow-sm">
                     <div class="card-header border-bottom-0 d-flex align-items-center">
                        <i class="bi bi-hand-thumbs-up fs-2"></i>
                     </div>
                     <div class="card-body text-end">
                        <h6 class="card-title">Likes</h6>
                        <h6 class="card-subtitle text-muted mb-2">456</h6>
                     </div>
                  </div>
               </div>
               <div class="col">
                  <div class="card flex-row shadow-sm">
                     <div class="card-header border-bottom-0 d-flex align-items-center">
                        <i class="bi bi-camera fs-2"></i>
                     </div>
                     <div class="card-body text-end">
                        <h6 class="card-title">Media</h6>
                        <h6 class="card-subtitle text-muted mb-2">456</h6>
                     </div>
                  </div>
               </div>
            </div>
         </section>
         <section>
            <div class="row row-cols-1 row-cols-lg-2 g-3">
               <div class="col">
                  <div class="card shadow-sm">
                     <h6 class="card-header">Published Articles</h6>
                     <div class="card-body">
                        <div>
                           <canvas id="PostChart"></canvas>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="col">
                  <div class="card shadow-sm">
                     <h6 class="card-header">Gained Views</h6>
                     <div class="card-body">
                        <div>
                           <canvas id="ViewChart"></canvas>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </section>
      </div>
   </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.2.1/chart.min.js"></script>
<script>
   const labels = [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
   ];
   const posts = {
      labels: labels,
      datasets: [{
         label: 'Monthley Posts',
         backgroundColor: 'rgb(255, 99, 132)',
         borderColor: 'rgb(255, 99, 132)',
         data: [0, 10, 5, 2, 20, 30],
      }]
   };
   const views = {
      labels: labels,
      datasets: [{
         label: 'Monthley Views',
         backgroundColor: 'rgb(132, 99, 255)',
         borderColor: 'rgb(132, 99, 255)',
         data: [0, 10, 5, 2, 20, 30],
      }]
   };

   const PostConfig = {
      type: 'bar',
      data: posts,
      options: {}
   };

   const ViewConfig = {
      type: 'line',
      data: views,
      options: {}
   };

   var PostChart = new Chart(
      document.getElementById('PostChart'),
      PostConfig
   );

   var ViewChart = new Chart(
      document.getElementById('ViewChart'),
      ViewConfig
   );
</script>