<? $this->layout('Shared/layout') ?>

<div class="container d-flex flex-row align-items-center justify-content-center" style="height: 500px;">
	<div class="card flex-grow-1 p-4 shadow" style="max-width: 400px">
		<div class="card-body">
			<form method="post" action="/user/account/login">
				<h2 class="text-center text-info">User Login</h2>
				<div class="mb-3">
					<label for="Username" class="form-label">Username</label>
					<input type="text" class="form-control" id="Username" name="Username" required>
				</div>
				<div class="mb-3">
					<label for="Password" class="form-label">Password</label>
					<input type="password" class="form-control" id="Password" name="Password" required>
				</div>
				<div class="mb-3 form-check">
					<input type="checkbox" class="form-check-input" id="Remember" name="Remember">
					<label class="form-check-label" for="Remember">Remember me</label>
				</div>
				<div class="d-grid gap-2">
					<button type="submit" class="btn btn-info text-white">Login</button>
				</div>
				<div class="text-center mt-3">
					Don't have an account? <a href="/user/account/register">Register</a>
				</div>
				<?= $this->Html->AntiforgeryToken() ?>
			</form>
		</div>
	</div>
</div>